AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  AI Requirements Quality Evaluator
  Serverless application for evaluating software requirements using Amazon Bedrock

# Global configuration for all Lambda functions
Globals:
  Function:
    Timeout: 30
    Runtime: nodejs20.x
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        LOG_LEVEL: INFO
        AWS_REGION_OVERRIDE: !Ref AWS::Region

Parameters:
  # Environment parameter for deployment stage
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - staging
      - prod
    Description: Deployment environment

  # Rate limiting configuration
  RateLimitMax:
    Type: Number
    Default: 10
    Description: Maximum requests per rate limit window

  RateLimitWindowSeconds:
    Type: Number
    Default: 60
    Description: Rate limit window duration in seconds

  # Bedrock model configuration
  BedrockModelId:
    Type: String
    Default: anthropic.claude-3-sonnet-20240229-v1:0
    Description: Amazon Bedrock model ID to use for evaluations

Resources:
  # =============================================================================
  # API Gateway
  # =============================================================================
  
  RequirementsEvaluatorApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: !Sub requirements-evaluator-api-${Environment}
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST,OPTIONS'"
        AllowHeaders: "'Content-Type,Authorization'"
        AllowOrigin: "'*'"
      # Enable request throttling at API level
      MethodSettings:
        - HttpMethod: '*'
          ResourcePath: '/*'
          ThrottlingBurstLimit: 100
          ThrottlingRateLimit: 50

  # =============================================================================
  # Lambda Function
  # =============================================================================
  
  EvaluateFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub requirements-evaluator-${Environment}
      CodeUri: backend/
      Handler: src/index.handler
      Description: Evaluates software requirements using Amazon Bedrock
      Environment:
        Variables:
          RATE_LIMIT_TABLE: !Ref RateLimitTable
          RATE_LIMIT_MAX: !Ref RateLimitMax
          RATE_LIMIT_WINDOW: !Ref RateLimitWindowSeconds
          BEDROCK_MODEL_ID: !Ref BedrockModelId
      Policies:
        # DynamoDB permissions for rate limiting
        - DynamoDBCrudPolicy:
            TableName: !Ref RateLimitTable
        # Bedrock permissions for AI evaluation
        - Statement:
            - Effect: Allow
              Action:
                - bedrock:InvokeModel
              Resource: 
                - !Sub arn:aws:bedrock:${AWS::Region}::foundation-model/${BedrockModelId}
      Events:
        EvaluateApi:
          Type: Api
          Properties:
            RestApiId: !Ref RequirementsEvaluatorApi
            Path: /evaluate
            Method: POST
        EvaluateOptionsApi:
          Type: Api
          Properties:
            RestApiId: !Ref RequirementsEvaluatorApi
            Path: /evaluate
            Method: OPTIONS

  # =============================================================================
  # DynamoDB Table for Rate Limiting
  # =============================================================================
  
  RateLimitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub requirements-evaluator-rate-limit-${Environment}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      Tags:
        - Key: Application
          Value: requirements-evaluator
        - Key: Environment
          Value: !Ref Environment

  # =============================================================================
  # S3 Bucket for Frontend
  # =============================================================================
  
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub requirements-evaluator-frontend-${Environment}-${AWS::AccountId}
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - '*'
            AllowedMethods:
              - GET
            AllowedOrigins:
              - '*'
      Tags:
        - Key: Application
          Value: requirements-evaluator
        - Key: Environment
          Value: !Ref Environment

  # Bucket policy for CloudFront access
  FrontendBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref FrontendBucket
      PolicyDocument:
        Statement:
          - Sid: AllowCloudFrontAccess
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: !Sub ${FrontendBucket.Arn}/*
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${CloudFrontDistribution}

  # =============================================================================
  # CloudFront Distribution
  # =============================================================================
  
  CloudFrontOriginAccessControl:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub requirements-evaluator-oac-${Environment}
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  CloudFrontDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub Requirements Evaluator - ${Environment}
        DefaultRootObject: index.html
        PriceClass: PriceClass_100
        
        # S3 Origin for frontend
        Origins:
          - Id: S3Origin
            DomainName: !GetAtt FrontendBucket.RegionalDomainName
            S3OriginConfig:
              OriginAccessIdentity: ''
            OriginAccessControlId: !Ref CloudFrontOriginAccessControl
          
          # API Gateway Origin
          - Id: ApiOrigin
            DomainName: !Sub ${RequirementsEvaluatorApi}.execute-api.${AWS::Region}.amazonaws.com
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols:
                - TLSv1.2

        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods:
            - GET
            - HEAD
            - OPTIONS
          CachedMethods:
            - GET
            - HEAD
          # AWS Managed Policy: CachingOptimized (658327ea-f89d-4fab-a63d-7e88639e58f6)
          # See: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true

        CacheBehaviors:
          # API routes go to API Gateway
          - PathPattern: /api/*
            TargetOriginId: ApiOrigin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods:
              - GET
              - HEAD
              - OPTIONS
              - PUT
              - POST
              - PATCH
              - DELETE
            # AWS Managed Policy: CachingDisabled (4135ea2d-6df8-44a3-9df3-4b5a84be39ad)
            # See: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-cache-policies.html
            CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
            # AWS Managed Policy: AllViewerExceptHostHeader (b689b0a8-53d0-40ab-baf2-68738e2966ac)
            # See: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/using-managed-origin-request-policies.html
            OriginRequestPolicyId: b689b0a8-53d0-40ab-baf2-68738e2966ac

        # Custom error responses for SPA routing
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: /index.html
          - ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: /index.html

      Tags:
        - Key: Application
          Value: requirements-evaluator
        - Key: Environment
          Value: !Ref Environment

  # =============================================================================
  # CloudWatch Dashboard
  # =============================================================================
  
  MonitoringDashboard:
    Type: AWS::CloudWatch::Dashboard
    Properties:
      DashboardName: !Sub requirements-evaluator-${Environment}
      DashboardBody: !Sub |
        {
          "widgets": [
            {
              "type": "metric",
              "x": 0,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Invocations",
                "metrics": [
                  ["AWS/Lambda", "Invocations", "FunctionName", "${EvaluateFunction}"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 0,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Errors",
                "metrics": [
                  ["AWS/Lambda", "Errors", "FunctionName", "${EvaluateFunction}"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 0,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "Lambda Duration",
                "metrics": [
                  ["AWS/Lambda", "Duration", "FunctionName", "${EvaluateFunction}"]
                ],
                "period": 300,
                "stat": "Average",
                "region": "${AWS::Region}"
              }
            },
            {
              "type": "metric",
              "x": 12,
              "y": 6,
              "width": 12,
              "height": 6,
              "properties": {
                "title": "API Gateway Requests",
                "metrics": [
                  ["AWS/ApiGateway", "Count", "ApiName", "requirements-evaluator-api-${Environment}"]
                ],
                "period": 300,
                "stat": "Sum",
                "region": "${AWS::Region}"
              }
            }
          ]
        }

  # =============================================================================
  # CloudWatch Alarms
  # =============================================================================
  
  LambdaErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub requirements-evaluator-lambda-errors-${Environment}
      AlarmDescription: Alarm when Lambda function has errors
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref EvaluateFunction

# =============================================================================
# Outputs
# =============================================================================

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL
    Value: !Sub https://${RequirementsEvaluatorApi}.execute-api.${AWS::Region}.amazonaws.com/${Environment}/evaluate

  CloudFrontDomain:
    Description: CloudFront distribution domain name
    Value: !GetAtt CloudFrontDistribution.DomainName

  CloudFrontUrl:
    Description: Full CloudFront URL
    Value: !Sub https://${CloudFrontDistribution.DomainName}

  FrontendBucketName:
    Description: S3 bucket for frontend assets
    Value: !Ref FrontendBucket

  LambdaFunctionArn:
    Description: Lambda function ARN
    Value: !GetAtt EvaluateFunction.Arn

  DashboardUrl:
    Description: CloudWatch Dashboard URL
    Value: !Sub https://${AWS::Region}.console.aws.amazon.com/cloudwatch/home?region=${AWS::Region}#dashboards:name=${MonitoringDashboard}
